openapi: 3.0.0
info:
  title: ChatRooms
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /loadchat/{ id }:
    get:
      tags:
        - ChatRoom
      summary: http://localhost:8080/loadchat/1
      parameters: 
        - in: path
          name: id
          schema:
            type: integer
            required: true
          description: Numeric ID of the chat to get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /deletechat/0:
    delete:
      tags:
        - ChatRoom
      summary: http://localhost:8080/deletechat/0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /newchat:
    post:
      tags:
        - ChatRoom
      summary: http://localhost:8080/newchat
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_ids:
                  - 2
                  - 3
                  - 4
                chatType: private
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /loadchats:
    get:
      tags:
        - ChatRoom
      summary: http://localhost:8080/loadchats
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /addusers/:
    post:
      tags:
        - ChatRooms
      summary: http://localhost:8080/addusers/
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                chat_id: 1
                user_ids:
                  - 4
                  - 6
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /messagesfrom/10:
    get:
      tags:
        - Messages
      summary: http://localhost:8080/messagesfrom/10
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /register:
    post:
      tags:
        - Users
      summary: http://localhost:8080/register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: token
                lastName: tester
                email: tt:gmail.com
                username: jwttest
                password: '123456'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login/:
    get:
      tags:
        - Users
      summary: http://localhost:8080/login/
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /:
    get:
      tags:
        - Users
      summary: http://localhost:8080/
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /updatedata/1:
    put:
      tags:
        - Users
      summary: http://localhost:8080/updatedata/1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: testtest@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete/1:
    delete:
      tags:
        - Users
      summary: http://localhost:8080/delete/1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /refreshToken:
    post:
      tags:
        -  WebTokens
      summary: http://localhost:8080/refreshToken
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /testAuth:
    get:
      tags:
        - WebTokens
      summary: http://localhost:8080/testAuth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

